"""initial_schema

Revision ID: 6a7eca3ecd69
Revises:
Create Date: 2026-09-13 09:23:53.143564

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a7eca3ecd69"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("source_provider", sa.String(length=16), nullable=False),
        sa.Column("destination_provider", sa.String(length=16), nullable=False),
        sa.Column("source_playlist_id", sa.String(length=256), nullable=False),
        sa.Column("destination_playlist_id", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("total_tracks", sa.Integer(), nullable=False),
        sa.Column("matched_tracks", sa.Integer(), nullable=False),
        sa.Column("transferred_tracks", sa.Integer(), nullable=False),
        sa.Column("failed_tracks", sa.Integer(), nullable=False),
        sa.Column("imported", sa.Boolean(), nullable=False),
        sa.Column("pending_write", sa.String(length=128), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("completed_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "request_key"),
    )
    op.create_index(
        op.f("ix_conversions_user_id"), "conversions", ["user_id"], unique=False
    )
    op.create_table(
        "demo_playlists",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tracks", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("verifier", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.Column("storefront", sa.String(length=16), nullable=False),
        sa.Column("provider_user_id", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider"),
    )
    op.create_index(
        op.f("ix_provider_accounts_user_id"),
        "provider_accounts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "track_mappings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("source_provider", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=256), nullable=False),
        sa.Column("destination_provider", sa.String(length=16), nullable=False),
        sa.Column("storefront", sa.String(length=16), nullable=False),
        sa.Column("destination", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "source_provider",
            "source_id",
            "destination_provider",
            "storefront",
        ),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversion_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("published_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversion_id"],
            ["conversions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_conversion_id"), "jobs", ["conversion_id"], unique=False
    )
    op.create_table(
        "track_matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversion_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source", sa.JSON(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("destination", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("transferred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversion_id"],
            ["conversions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversion_id", "position"),
    )
    op.create_index(
        op.f("ix_track_matches_conversion_id"),
        "track_matches",
        ["conversion_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_track_matches_conversion_id"), table_name="track_matches")
    op.drop_table("track_matches")
    op.drop_index(op.f("ix_jobs_conversion_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("track_mappings")
    op.drop_index(op.f("ix_provider_accounts_user_id"), table_name="provider_accounts")
    op.drop_table("provider_accounts")
    op.drop_table("oauth_states")
    op.drop_table("demo_playlists")
    op.drop_index(op.f("ix_conversions_user_id"), table_name="conversions")
    op.drop_table("conversions")
    op.drop_table("users")
    # ### end Alembic commands ###
